version: "3"

services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./app:/home/myuser/app
    tty: true
    restart: always
    ports:
      - 5000:5000
